# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, help_text='First Name', max_length=512)),
                ('last_name', models.CharField(db_index=True, help_text='Last Name', max_length=512, null=True)),
                ('address', models.CharField(blank=True, help_text='Street address', max_length=500, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('zip', models.CharField(blank=True, help_text='Zipcode', max_length=10, null=True)),
                ('region', models.CharField(blank=True, help_text='Region', max_length=50, null=True)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=50, null=True)),
            ],
        ),
    ]
