# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20160925_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'Male', b'Male'), (b'Female', b'Female'), (b'Other', b'Other'), (b'Prefer not to say', b'Prefer not to say')], max_length=30, null=True),
        ),
    ]
