# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20160925_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='region',
        ),
    ]
