# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20160925_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='event_end_date_time',
            field=models.DateTimeField(help_text='Example format: 10/25/2006 14:30'),
        ),
        migrations.AlterField(
            model_name='program',
            name='event_start_date_time',
            field=models.DateTimeField(help_text='Example format: 10/25/2006 14:30'),
        ),
    ]
