# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_staffcontact'),
        ('programs', '0003_auto_20160925_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='students',
            field=models.ManyToManyField(to='students.Student'),
        ),
    ]
